/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// ✅ Cache the manifest.json and favicon.ico to handle offline access.
precacheAndRoute([
  { url: '/manifest.json', revision: null },
  { url: '/favicon.ico', revision: null },
]);

// ✅ Cache API requests (like TMDB)
registerRoute(
  ({ url }) => url.origin.includes('api.themoviedb.org'),
  new StaleWhileRevalidate({
    cacheName: 'tmdb-api-cache',
  })
);

// ✅ Cache images (like movie posters)
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
  })
);

// ✅ Optional: Cache other important assets (CSS, JS)
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// ✅ Optional: Listen to 'install' event to force update
self.addEventListener('install', (event) => {
  console.log('Service Worker installing.');
  self.skipWaiting();
});

// ✅ Optional: Listen to 'activate' event
self.addEventListener('activate', (event) => {
  console.log('Service Worker activated.');
});
